application: bikes-against-the-machine
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /assets/(.*)
  static_files: assets/\1
  upload: assets/(.*)

- url: /.*
  script: controller.app
